// @generated by astro-linter
// Re-run "npx astro add astro-linter" to update
import base from 'astro-linter/config'
import typescript from 'astro-linter/config/typescript'
import react from 'astro-linter/config/react'

export default [
  ...base,
  ...typescript,
  ...react,
  // Add your custom rules here
]
